version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: movie-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: moviebooking
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: movie-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/moviebooking
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234

      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: true
      SPRING_SQL_INIT_MODE: always

      APP_JWT_REFRESH_EXPIRATION_IN_SECONDS: 2592000
      APP_JWT_ACCESS_EXPIRATION_IN_SECONDS: 3600
      APP_JWT_ACCESS_ADMIN_EXPIRATION_IN_SECONDS: 28800
      APP_JWT_BASE64_SECRETKEY: g5r...

    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: movie-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql-data:
